### PR TITLE
Use StructPropertyValue for untagged StructProperty

### PR DESCRIPTION
**Pull request by scottanderson**
This improves #114 by separating the code for property tags from the code for property values.

### CODE REVIEW

**Comment by localcc** [comment]
looks good, but maybe call it `UntaggedStructProperty`? Considering it's a property itself and calling it with a `Value` suffix is a bit confusing.

**Comment by scottanderson** [comment]
Thanks for the suggestion, @localcc! I agree it's worth reassessing struct names across the board. That said, I believe we consistently refer to property tags as (unqualified) "properties" and the property data as "values," so I'd prefer not to make this change in this PR unless you feel it's critical. That said, I fully support transitioning to more specific names (e.g., `Tagged*` and `Untagged*`) across the board. I'm happy to open a new issue to explore the best approach and track updates for all properties. Does that sound like the right path forward to you?

**Comment by localcc** [comment]
Good point, let's leave it like this in this PR and think about it in a new issue that's focused specifically on naming.

**Comment by localcc** [comment]
Thanks for the contribution!

**Pull request merged**
